[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1_rMzgRXBV3hTn5meZhKUF8LoIemHbIBxGOsv8HPaQMc/edit?usp=sharing"

[connections.gsheets2]
spreadsheet = "https://docs.google.com/spreadsheets/d/19LBjbtCMDBn9Qyl8Ht3eSgIea3zVpiqrM6D9JPEMO1Y/edit"
